<?php

return [

    [
        'number' => '01',
        'title' => 'Hostel Management System',
        'category' => 'Laravel / PHP',
        'type' => 'Client Project',

        'description' => 'A complete hostel management platform for managing students, admissions, rooms, beds, staff, attendance, payments and mess subscriptions.',

        'technologies' => [
            'Laravel',
            'PHP',
            'MySQL',
            'Bootstrap',
            'REST API',
        ],

        'image' => 'assets/images/projects/hostel-management.jpg',

        'live_url' => '#',
        'github_url' => 'https://github.com/N-web-coder/hms',

        'features' => [
            'Role-based Admin, Staff and Student dashboards',
            'User registration, login and password reset',
            'Student admission and approval management',
            'Student profile and admission record management',
            'Hostel room and bed management',
            'Room and bed allocation and reassignment',
            'Bed availability and occupancy management',
            'Staff registration and management',
            'Staff attendance tracking and history',
            'Staff salary and payment management',
            'Student payment records and payment history',
            'Mess subscription management',
            'Monthly payment management',
            'Student and staff enquiry management',
            'Enquiry replies and status tracking',
            'Invoice creation and PDF downloads',
            'Student payment PDF generation',
            'Staff salary slip generation',
            'Deleted room and bed recovery',
            'Company information management',
        ],
    ],

    [
        'number' => '02',
        'title' => 'Library Management System',
        'category' => 'Laravel / MySQL',
        'type' => 'Client Project',

        'description' => 'Multi-role library management platform with Admin, Staff and Student portals, authentication, role-based access control and payment tracking.',

        'technologies' => [
            'Laravel',
            'PHP',
            'MySQL',
            'Razorpay',
            'RBAC',
        ],

        'image' => 'assets/images/projects/library-management.jpg',

        'live_url' => '#',
        'github_url' => 'https://github.com/N-web-coder/lms',

        'features' => [
            'Separate Admin, Staff and Student portals',
            'User registration and authentication',
            'Role-based access control',
            'Admin dashboard',
            'Staff management',
            'Student management',
            'Library record management',
            'Student account and record tracking',
            'Payment tracking',
            'Centralized library administration',
        ],
    ],

    [
        'number' => '03',
        'title' => 'Wedding & Event Management Platform',
        'category' => 'Laravel / PHP',
        'type' => 'Client Project',

        'description' => 'A fully dynamic wedding and event management platform built with Laravel, designed to showcase and manage wedding-related services including weddings, anniversaries, birthdays, engagements, receptions, catering, decoration, photography, venues and honeymoon packages. The platform includes a complete admin panel for managing categories, services, gallery content and locations, with dynamic service pages and location-based service discovery.',

        'technologies' => [
            'Laravel',
            'PHP',
            'MySQL',
            'Bootstrap',
            'JavaScript',
            'Blade Templates',
            'REST API',
        ],

        'image' => 'assets/images/projects/wedding-event.jpg',

        'live_url' => '#',
        'github_url' => 'https://github.com/N-web-coder/weddingeventwala',

        'features' => [
            'Fully dynamic wedding and event website',
            'Dynamic homepage and service sections',
            'Dynamic service detail pages',
            'Wedding service management',
            'Anniversary event services',
            'Birthday event services',
            'Catering services',
            'Decoration and decorator services',
            'Engagement event services',
            'Honeymoon packages',
            'Photography services',
            'Reception services',
            'Theme entry services',
            'Venue management',
            'Wedding services',
            'Dynamic category management',
            'Dynamic service management',
            'Gallery management',
            'Location management',
            'Location-based service discovery',
            'Nearest service detection',
            'Admin authentication',
            'Admin dashboard',
            'Service CRUD operations',
            'Category CRUD operations',
            'Gallery CRUD operations',
            'Location CRUD operations',
            'Dynamic content management',
            'Responsive frontend',
        ],
    ],

    [
        'number' => '04',
        'title' => 'Education & College Admission Platform',
        'category' => 'Laravel / PHP',
        'type' => 'Client Project',

        'description' => 'A fully dynamic education and college admission platform built with Laravel, designed to provide students with information about courses, colleges, scholarships, syllabus, announcements and participating institutes. The platform includes an AI-powered assistant, candidate enquiry system, dynamic content management and a comprehensive admin panel for managing colleges, courses, scholarships, documents, candidate profiles, FAQs, policies and website content.',

        'technologies' => [
            'Laravel',
            'PHP',
            'MySQL',
            'Bootstrap',
            'JavaScript',
            'Blade Templates',
            'REST API',
            'AI Integration',
        ],

        'image' => 'assets/images/projects/education-platform.jpg',

        'live_url' => 'https://ejcet.ai/',
        'github_url' => 'https://github.com/N-web-coder/educationJI',

        'features' => [
            'Fully dynamic education platform',
            'Dynamic homepage content management',
            'College listing and management',
            'Bulk college import using CSV',
            'College data filtering and management',
            'Top and participating college management',
            'Course and course category management',
            'Scholarship information management',
            'Syllabus and syllabus pattern management',
            'Information bulletin management',
            'Educational document and announcement management',
            'Candidate profile management',
            'Student registration and enquiry system',
            'College and course information pages',
            'Participating institute listing',
            'AI-powered Ask AI assistant',
            'FAQ management',
            'Contact information management',
            'Dynamic website header management',
            'Dynamic navigation menu management',
            'Hero section management',
            'Notice and announcement management',
            'Current event management',
            'About section management',
            'Privacy policy management',
            'Terms and conditions management',
            'Refund policy management',
            'Disclaimer management',
            'Copyright policy management',
            'Admin authentication',
            'Admin dashboard',
            'CRUD-based content management',
            'Candidate enquiry management',
            'Responsive education website',
        ],
    ],

    [
        'number' => '05',
        'title' => 'AI PDF Question Answering',
        'category' => 'AI / RAG',
        'type' => 'AI Project',

        'description' => 'AI-powered document Q&A application that allows users to upload PDFs and ask questions using document processing, embeddings and vector search.',

        'technologies' => [
            'Python',
            'LangChain',
            'RAG',
            'Vector Search',
            'LLM',
        ],

        'image' => 'assets/images/projects/ai-pdf-qa.jpg',

        'live_url' => '#',
        'github_url' => '#',

        'features' => [
            'PDF document upload',
            'Document text extraction',
            'Text splitting',
            'Embeddings',
            'Vector retrieval',
            'AI-generated answers',
        ],
    ],

    [
        'number' => '06',
        'title' => 'AI Text Summarizer',
        'category' => 'GenAI / FastAPI',
        'type' => 'Personal Project',
        'description' => 'An AI-powered text summarization application built with FastAPI, LangChain and Groq LLM. The application allows users to generate simple, professional or bullet-point summaries with selectable short, medium and detailed output lengths through a responsive web interface.',
        'technologies' => [
            'Python',
            'FastAPI',
            'Uvicorn',
            'LangChain',
            'LangChain Core',
            'LangChain Groq',
            'Groq LLM',
            'Pydantic',
            'Jinja2',
            'HTML',
            'CSS',
            'JavaScript',
            'REST API',
        ],
        'image' => 'assets/images/projects/ai-text-summarizer.jpg',
        'live_url' => 'https://summarizer-dw9j.onrender.com/',
        'github_url' => 'https://github.com/N-web-coder/summarizer',
        'features' => [
            'AI-powered text summarization',
            'Simple summary generation',
            'Professional summary generation',
            'Bullet-point summary generation',
            'Short summary length',
            'Medium summary length',
            'Detailed summary length',
            'Word counter',
            'Character counter',
            'Copy generated summary',
            'Clear text functionality',
            'Loading indicator',
            'API error handling',
            'FastAPI REST API',
            'Responsive web interface',
            'Swagger API documentation',
            'Pydantic request validation',
            'LangChain prompt management',
            'ChatPromptTemplate integration',
            'Groq LLM integration',
            'Environment variable configuration',
        ],
    ],

];
